language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
install: pip install . pep8 pyflakes --use-mirrors
before_script: "cp cartridge/project_template/local_settings.py.template cartridge/project_template/local_settings.py"
script: ./cartridge/project_template/manage.py test
