language: python
env:
  - DJANGO="Django>=1.8.0,<1.9.0"
  - DJANGO="Django>=1.9.0,<1.10.0"
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install $DJANGO
  - pip install -e git://github.com/stephenmcd/mezzanine.git#egg=mezzanine
  - pip install . --allow-unverified pyPdf
script:
  - python setup.py test
notifications:
  irc: "irc.freenode.org#mezzanine"
  on_success: change
  on_failure: change
